/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

fn main() {
	let mut m = 1;
	let mut n = 2;
	let mut tmp;
	let mut sum = 0;

	while n < 4_000_000 {
		tmp = n;
		n = m + n;
		m = tmp;

		if m % 2 == 0 {
			sum += m;
		}
	}

	println!("{:?}", sum);
}