[package]
name = "day10"
version = "0.1.0"
authors = ["Patrick MARIE <pm@mkz.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mkz_aoc = { version = "0.1.0", git = "https://git.mkz.me/mycroft/mkz_aoc.git" }
